# Generated by Django 3.0.7 on 2020-07-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osp', '0009_form_close'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='close',
        ),
        migrations.AlterField(
            model_name='form',
            name='published_status',
            field=models.CharField(choices=[('published', 'Published'), ('unpublished', 'Unpublished'), ('closed', 'Closed')], default='unpublished', max_length=11),
        ),
    ]
