# Generated by Django 3.0.7 on 2020-07-23 14:21

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("osp", "0010_auto_20200713_1843"),
    ]

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("question", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="osp.Question")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CheckboxValue",
            fields=[
                (
                    "answer_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="osp.Answer",
                    ),
                ),
                (
                    "value",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=255), size=None
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("osp.answer",),
        ),
        migrations.CreateModel(
            name="ChoiceValue",
            fields=[
                (
                    "answer_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="osp.Answer",
                    ),
                ),
                ("value", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
            bases=("osp.answer",),
        ),
        migrations.CreateModel(
            name="DateValue",
            fields=[
                (
                    "answer_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="osp.Answer",
                    ),
                ),
                ("value", models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                "abstract": False,
            },
            bases=("osp.answer",),
        ),
        migrations.CreateModel(
            name="DropdownValue",
            fields=[
                (
                    "answer_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="osp.Answer",
                    ),
                ),
                ("value", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
            bases=("osp.answer",),
        ),
        migrations.CreateModel(
            name="FileUploadValue",
            fields=[
                (
                    "answer_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="osp.Answer",
                    ),
                ),
                ("value", models.TextField()),
            ],
            options={
                "abstract": False,
            },
            bases=("osp.answer",),
        ),
        migrations.CreateModel(
            name="ParagraphValue",
            fields=[
                (
                    "answer_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="osp.Answer",
                    ),
                ),
                ("value", models.TextField()),
            ],
            options={
                "abstract": False,
            },
            bases=("osp.answer",),
        ),
        migrations.CreateModel(
            name="ShortAnswerValue",
            fields=[
                (
                    "answer_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="osp.Answer",
                    ),
                ),
                ("value", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
            bases=("osp.answer",),
        ),
        migrations.CreateModel(
            name="TimeValue",
            fields=[
                (
                    "answer_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="osp.Answer",
                    ),
                ),
                ("value", models.TimeField(default=django.utils.timezone.now)),
            ],
            options={
                "abstract": False,
            },
            bases=("osp.answer",),
        ),
        migrations.CreateModel(
            name="FormFeedback",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "acceptance_status",
                    models.CharField(
                        choices=[
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("waitlisted", "Waitlisted"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "answers",
                    models.ManyToManyField(blank=True, default=None, related_name="form_answers", to="osp.Answer"),
                ),
                ("form", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="osp.Form")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
