# Generated by Django 3.0.7 on 2020-08-10 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("osp", "0012_auto_20200723_1626"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinformation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="user_name", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
