# Generated by Django 3.0.7 on 2020-08-24 19:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osp", "0013_auto_20200810_1406"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinformation",
            name="zulip_id",
            field=models.BigIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="ZulipStat",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("zulip_username", models.TextField(blank=True)),
                ("total_messages", models.BigIntegerField(default=0)),
                ("last_activity", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user_information",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="osp.UserInformation"),
                ),
            ],
        ),
    ]
