# Generated by Django 3.0.7 on 2020-08-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osp", "0015_zulipstat_first_activity"),
    ]

    operations = [
        migrations.AddField(
            model_name="zulipstat",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
