# Generated by Django 3.0.7 on 2020-08-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osp", "0016_zulipstat_updated_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="zulipstat",
            name="celebrate_messages",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="zulipstat",
            name="general_messages",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="zulipstat",
            name="newcomers_messages",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="zulipstat",
            name="opportunities_messages",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="zulipstat",
            name="questions_messages",
            field=models.BigIntegerField(default=0),
        ),
    ]
