# Generated by Django 3.0.7 on 2021-03-09 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osp", "0017_auto_20200824_2008"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinformation",
            name="github_username",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.CreateModel(
            name="GithubStat",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("total_prs_open", models.IntegerField(default=0)),
                ("total_prs_closed", models.IntegerField(default=0)),
                ("total_prs_merged", models.IntegerField(default=0)),
                ("total_issues_created", models.IntegerField(default=0)),
                ("total_comments_on_issues", models.IntegerField(default=0)),
                ("total_prs_reviewed", models.IntegerField(default=0)),
                (
                    "user_information",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="osp.UserInformation"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
